"""empty message

Revision ID: 076801d448a6
Revises: 6232bab9f45b
Create Date: 2020-12-06 09:24:37.100091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076801d448a6'
down_revision = '6232bab9f45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('registration', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration', 'updated_at')
    op.drop_column('registration', 'created_at')
    # ### end Alembic commands ###
