version: '3.7'

networks:
  web-programming:
    name: web-programming
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24

services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "80:8000"
    volumes:
      - ./app:/app
    networks:
      - web-programming

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "6432:5432"
    networks:
      - web-programming
